### ISSUE TITLE
Support <Infra>MachineTemplate

### ISSUE THREAD

**Issue by chuckha** [ashish-amarnath/capi-yaml-gen#16]
This should also support MachineDeployments + templates.

Not sure what the API for that will look like...

Maybe it's just a flag

`--machine-deployment` - Produces a machine deployment for worker nodes instead of raw Machines.

**Comment by chuckha** [comment]
here is a working example:

```
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: DockerCluster
metadata:
  creationTimestamp: null
  name: my-cluster
  namespace: default
spec: {}
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: my-cluster
  namespace: default
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: DockerCluster
    name: my-cluster
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: DockerMachine
metadata:
  creationTimestamp: null
  name: controlplane-0
  namespace: default
spec: {}
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: Machine
metadata:
  creationTimestamp: null
  labels:
    cluster.x-k8s.io/cluster-name: my-cluster
    cluster.x-k8s.io/control-plane: "true"
  name: controlplane-0
  namespace: default
spec:
  bootstrap:
    configRef:
      apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
      kind: KubeadmConfig
      name: controlplane-0-config
      namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: DockerMachine
    name: controlplane-0
    namespace: default
  metadata: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfig
metadata:
  creationTimestamp: null
  name: controlplane-0-config
  namespace: default
spec:
  clusterConfiguration:
    apiServer: {}
    certificatesDir: ""
    controlPlaneEndpoint: ""
    controllerManager: {}
    dns:
      type: ""
    etcd: {}
    imageRepository: ""
    kubernetesVersion: ""
    networking:
      dnsDomain: ""
      podSubnet: ""
      serviceSubnet: ""
    scheduler: {}
  initConfiguration:
    localAPIEndpoint:
      advertiseAddress: ""
      bindPort: 0
    nodeRegistration: {}
---
apiVersion: cluster.x-k8s.io/v1alpha2
kind: MachineDeployment
metadata:
  name: my-cluster-md-0
  labels:
    cluster.x-k8s.io/cluster-name: my-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: my-cluster
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: my-cluster
    spec:
      version: v1.15.3
      bootstrap:
        configRef:
          name: my-cluster-md-0
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: my-cluster-md-0
        kind: DockerMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: DockerMachineTemplate
metadata:
  name: my-cluster-md-0
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha2
kind: KubeadmConfigTemplate
metadata:
  name: my-cluster-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration: {}
```
